#!/bin/bash
# Condor submission script
# Generated with submit_job.py at 2016-01-21 09:53:06.837632
# The command was: /afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis//Utilities/scripts/submit_job.py MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py --campaign-tag=RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1 --samples ST* TT_Tune* -o submit_MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_TTandST_LFV.sh

# Submit file for sample ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/dags/daginputs/ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/dags/daginputs/ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags/daginputs/ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-ST_t-channel_antitop_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags/daginputs/ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-ST_t-channel_top_4f_leptonDecays_13TeV-powheg-pythia8_TuneCUETP8M1 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample ST_tW_antitop_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_antitop_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_antitop_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_antitop_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_antitop_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_antitop_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags/daginputs/ST_tW_antitop_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-ST_tW_antitop_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags/daginputs/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample ST_tW_top_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_top_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_top_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_top_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_top_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ST_tW_top_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/dags/daginputs/ST_tW_top_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-ST_tW_top_5f_DS_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample TT_TuneCUETP8M1_13TeV-amcatnlo-pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TT_TuneCUETP8M1_13TeV-amcatnlo-pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TT_TuneCUETP8M1_13TeV-amcatnlo-pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TT_TuneCUETP8M1_13TeV-amcatnlo-pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TT_TuneCUETP8M1_13TeV-amcatnlo-pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TT_TuneCUETP8M1_13TeV-amcatnlo-pythia8/dags/daginputs/TT_TuneCUETP8M1_13TeV-amcatnlo-pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-TT_TuneCUETP8M1_13TeV-amcatnlo-pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample TT_TuneCUETP8M1_13TeV-powheg-pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TT_TuneCUETP8M1_13TeV-powheg-pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TT_TuneCUETP8M1_13TeV-powheg-pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TT_TuneCUETP8M1_13TeV-powheg-pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TT_TuneCUETP8M1_13TeV-powheg-pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TT_TuneCUETP8M1_13TeV-powheg-pythia8/dags/daginputs/TT_TuneCUETP8M1_13TeV-powheg-pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-TT_TuneCUETP8M1_13TeV-powheg-pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
