#!/bin/bash
# Condor submission script
# Generated with submit_job.py at 2016-01-21 04:10:03.612840
# The command was: /afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis//Utilities/scripts/submit_job.py MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py --campaign-tag=RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v1 --samples WW_TuneCUET* ZZ_TuneCUET* WZ_TuneCUET* TTJets_TuneCUET* WJetsToLNu_TuneCUET* DYJetsToLL_M-50_TuneCUET* *HToEMu* *HToETau* *HToMuTau* VBFHToTauTau* GluGluHToTauTau* -o submit_MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV.sh

# Submit file for sample WW_TuneCUETP8M1_13TeV-pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WW_TuneCUETP8M1_13TeV-pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WW_TuneCUETP8M1_13TeV-pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WW_TuneCUETP8M1_13TeV-pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WW_TuneCUETP8M1_13TeV-pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WW_TuneCUETP8M1_13TeV-pythia8/dags/daginputs/WW_TuneCUETP8M1_13TeV-pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-WW_TuneCUETP8M1_13TeV-pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample WZ_TuneCUETP8M1_13TeV-pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WZ_TuneCUETP8M1_13TeV-pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WZ_TuneCUETP8M1_13TeV-pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WZ_TuneCUETP8M1_13TeV-pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WZ_TuneCUETP8M1_13TeV-pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WZ_TuneCUETP8M1_13TeV-pythia8/dags/daginputs/WZ_TuneCUETP8M1_13TeV-pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-WZ_TuneCUETP8M1_13TeV-pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample GluGluHToTauTau_M125_13TeV_powheg_pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGluHToTauTau_M125_13TeV_powheg_pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGluHToTauTau_M125_13TeV_powheg_pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGluHToTauTau_M125_13TeV_powheg_pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGluHToTauTau_M125_13TeV_powheg_pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGluHToTauTau_M125_13TeV_powheg_pythia8/dags/daginputs/GluGluHToTauTau_M125_13TeV_powheg_pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-GluGluHToTauTau_M125_13TeV_powheg_pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample GluGlu_LFV_HToEMu_M125_13TeV_powheg_pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGlu_LFV_HToEMu_M125_13TeV_powheg_pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGlu_LFV_HToEMu_M125_13TeV_powheg_pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGlu_LFV_HToEMu_M125_13TeV_powheg_pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGlu_LFV_HToEMu_M125_13TeV_powheg_pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGlu_LFV_HToEMu_M125_13TeV_powheg_pythia8/dags/daginputs/GluGlu_LFV_HToEMu_M125_13TeV_powheg_pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-GluGlu_LFV_HToEMu_M125_13TeV_powheg_pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample GluGlu_LFV_HToETau_M125_13TeV_powheg_pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGlu_LFV_HToETau_M125_13TeV_powheg_pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGlu_LFV_HToETau_M125_13TeV_powheg_pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGlu_LFV_HToETau_M125_13TeV_powheg_pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGlu_LFV_HToETau_M125_13TeV_powheg_pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/GluGlu_LFV_HToETau_M125_13TeV_powheg_pythia8/dags/daginputs/GluGlu_LFV_HToETau_M125_13TeV_powheg_pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-GluGlu_LFV_HToETau_M125_13TeV_powheg_pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/dags/daginputs/TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-TTJets_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample ZZ_TuneCUETP8M1_13TeV-pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ZZ_TuneCUETP8M1_13TeV-pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ZZ_TuneCUETP8M1_13TeV-pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ZZ_TuneCUETP8M1_13TeV-pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ZZ_TuneCUETP8M1_13TeV-pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/ZZ_TuneCUETP8M1_13TeV-pythia8/dags/daginputs/ZZ_TuneCUETP8M1_13TeV-pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-ZZ_TuneCUETP8M1_13TeV-pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample VBF_LFV_HToEMu_M125_13TeV_powheg_pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToEMu_M125_13TeV_powheg_pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToEMu_M125_13TeV_powheg_pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToEMu_M125_13TeV_powheg_pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToEMu_M125_13TeV_powheg_pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToEMu_M125_13TeV_powheg_pythia8/dags/daginputs/VBF_LFV_HToEMu_M125_13TeV_powheg_pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-VBF_LFV_HToEMu_M125_13TeV_powheg_pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample VBF_LFV_HToETau_M125_13TeV_powheg_pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToETau_M125_13TeV_powheg_pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToETau_M125_13TeV_powheg_pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToETau_M125_13TeV_powheg_pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToETau_M125_13TeV_powheg_pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToETau_M125_13TeV_powheg_pythia8/dags/daginputs/VBF_LFV_HToETau_M125_13TeV_powheg_pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-VBF_LFV_HToETau_M125_13TeV_powheg_pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8/dags/daginputs/VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-VBF_LFV_HToMuTau_M125_13TeV_powheg_pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/dags/daginputs/WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-WJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/dags/daginputs/WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample VBFHToTauTau_M125_13TeV_powheg_pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBFHToTauTau_M125_13TeV_powheg_pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBFHToTauTau_M125_13TeV_powheg_pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBFHToTauTau_M125_13TeV_powheg_pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBFHToTauTau_M125_13TeV_powheg_pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/VBFHToTauTau_M125_13TeV_powheg_pythia8/dags/daginputs/VBFHToTauTau_M125_13TeV_powheg_pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-VBFHToTauTau_M125_13TeV_powheg_pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/dags/daginputs/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
# Submit file for sample DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/dags/daginputs/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetEtaFix_LFV-DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=1 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName'
