#!/bin/bash
# Condor submission script
# Generated with submit_job.py at 2016-01-21 05:54:52.524407
# The command was: /afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis//Utilities/scripts/submit_job.py MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=0 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py --das-replace-tuple /afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14/src/FinalStateAnalysis/MetaData/tuples/MiniAOD-13TeV_Data.json --apply-cmsRun-lumimask --data --samples=data_SingleMuon_* -o submit_MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData.sh

# Submit file for sample data_SingleMuon_Run2015C_05Oct2015_25ns
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015C_05Oct2015_25ns/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015C_05Oct2015_25ns/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015C_05Oct2015_25ns/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015C_05Oct2015_25ns/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015C_05Oct2015_25ns/dags/daginputs/data_SingleMuon_Run2015C_05Oct2015_25ns_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData-data_SingleMuon_Run2015C_05Oct2015_25ns make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=0 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName' lumiMask=/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions15/13TeV/Cert_246908-260627_13TeV_PromptReco_Collisions15_25ns_JSON.txt
# Submit file for sample data_SingleMuon_Run2015D_05Oct2015_25ns
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015D_05Oct2015_25ns/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015D_05Oct2015_25ns/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015D_05Oct2015_25ns/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015D_05Oct2015_25ns/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015D_05Oct2015_25ns/dags/daginputs/data_SingleMuon_Run2015D_05Oct2015_25ns_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData-data_SingleMuon_Run2015D_05Oct2015_25ns make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=0 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName' lumiMask=/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions15/13TeV/Cert_246908-260627_13TeV_PromptReco_Collisions15_25ns_JSON.txt
# Submit file for sample data_SingleMuon_Run2015D_PromptReco-v4_25ns
mkdir -p /nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015D_PromptReco-v4_25ns/dags
farmoutAnalysisJobs --infer-cmssw-path "--submit-dir=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015D_PromptReco-v4_25ns/submit" "--output-dag-file=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015D_PromptReco-v4_25ns/dags/dag" "--output-dir=srm://cmssrm.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs/store/user/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015D_PromptReco-v4_25ns/" --input-files-per-job=1 --input-file-list=/nfs_scratch/aglevine/MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData/data_SingleMuon_Run2015D_PromptReco-v4_25ns/dags/daginputs/data_SingleMuon_Run2015D_PromptReco-v4_25ns_inputfiles.txt --assume-input-files-exist --input-dir=root://cmsxrootd.fnal.gov/ MiniAodV2For25ns_ExtraJets_JesUes_JetFix_LFVData-data_SingleMuon_Run2015D_PromptReco-v4_25ns make_ntuples_cfg.py channels=mmt,et,mt,em,eet,mm,mmm,emm nExtraJets=6 isMC=0 use25ns=1 paramFile=/afs/hep.wisc.edu/cms/aglevine/FSA_MiniAod/CMSSW_7_4_14_LFV/src/FinalStateAnalysis/NtupleTools/python/parameters/lfvh.py 'inputFiles=$inputFileNames' 'outputFile=$outputFileName' lumiMask=/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions15/13TeV/Cert_246908-260627_13TeV_PromptReco_Collisions15_25ns_JSON.txt
